# Generated by Django 4.1.5 on 2023-01-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=1000)),
                ('lastname', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('phonenumber', models.CharField(max_length=1000)),
                ('zipcode', models.CharField(max_length=500)),
                ('dayofbirth', models.CharField(max_length=50)),
                ('monthofbirth', models.CharField(max_length=50)),
                ('yearofbirth', models.CharField(max_length=50)),
                ('minimumtransaction', models.DecimalField(decimal_places=2, max_digits=70)),
                ('maximumtransaction', models.DecimalField(decimal_places=2, max_digits=70)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('nameoncard', models.CharField(max_length=1000)),
                ('cardnumber', models.CharField(max_length=100)),
                ('expiryday', models.CharField(max_length=50)),
                ('expirymonth', models.CharField(max_length=50)),
                ('expiryyear', models.CharField(max_length=50)),
            ],
        ),
    ]
