# Generated by Django 4.1.5 on 2023-01-13 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='dayofbirth',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='monthofbirth',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='yearofbirth',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='password1',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='password2',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
