# Generated by Django 4.1.5 on 2023-02-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsystem', '0003_alter_userdetail_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='acctnumber',
            field=models.IntegerField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='cardtype',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='cvv',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
